/* Main.c file generated by New Project wizard
 *
 * Created:   ÖÜ¶þ 9ÔÂ 19 2023
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
#include "lcd1602.h"
#include "keyboard.h"
void main(void)
 { 
   // Write your code here
   while (1)
   {
      init();
   }
}